plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  SuggestExtensions: false
  DisabledByDefault: false

Rails/ActionOrder:
  Enabled: false
Rails/ActionFilter:
  Enabled: false
Rails/FilePath:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Generators can have longer methods
Metrics/MethodLength:
  Exclude:
    - 'lib/generators/**/*'

Metrics/AbcSize:
  Exclude:
    - 'lib/generators/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/generators/kozenet_ui/install/install_generator.rb'

# Style/Documentation:
#   Exclude:
#     - 'spec/**/*'
#     - 'test/**/*'
