name: Kozenet UI CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ruby:
    runs-on: ubuntu-latest
    name: Ruby CI
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true

  test:
    runs-on: ubuntu-latest
    name: Test CI
    needs: ruby
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true
      - name: Generate dummy app for engine testing
        run: |
          bundle exec rails new spec/dummy --skip-test --skip-git --skip-bundle --skip-javascript --skip-hotwire --skip-action-mailer --skip-action-mailbox --skip-action-text --skip-active-record --skip-active-job --skip-active-storage --skip-action-cable --skip-jbuilder --skip-bootsnap --skip-keeps --skip-puma --skip-sprockets --skip-turbolinks --skip-spring --skip-listen --skip-coffee --skip-yarn --skip-webpack-install --skip-gemfile --skip-ci --skip-dev-gems
      - name: Remove Sprockets config from dummy app
        run: rm -f spec/dummy/config/initializers/assets.rb
      - name: Run the default task
        run: bundle exec rake
